# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
