# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_essay_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
