# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_educationentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationentry',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
