# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_educationentry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationentry',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
