# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_educationentry_update_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='issue',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='publisher',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='url_of_original_article',
            field=models.URLField(default=''),
        ),
    ]
