# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_add_content_and_meta_to_essay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.TextField(default='')),
            ],
        ),
    ]
