# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_teachingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='position',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='school',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
