# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_teachingentry_allow_blank_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_to_code',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_to_site',
            field=models.URLField(blank=True, default=''),
        ),
    ]
